#!/bin/bash

# Desired filename
FILENAME="*\\'\"Best School\"\\*$?******:)"

# Desired content
CONTENT="Best School\n"

# Create the file with the desired content
echo -e "$CONTENT" > "$FILENAME"

echo "File '$FILENAME' created with content:"
cat "$FILENAME"
