#!/bin/bash

# Define the file name
file_name="*\\'\"Best School\"'\\*$?*****:)"

# Create the file with the desired content
echo "Best School\n" > "$file_name"

# Print the file's contents
cat "$file_name"
