#!/bin/bash

# Desired file name
FILENAME='*\\'"Best School"'\\*$?******:)'

# Text content
TEXT="Best School
"

# Create the file
echo  "$TEXT" > "$FILENAME"

echo "File '$FILENAME' created with content:"
cat "$FILENAME"
